# Site settings
title: "PlaywithRobots: Tutorials on making and using Robots"
email: info@playwithrobots.com
description: "PlaywithRobots is all about making and using robots to do various fun stuff."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://playwithrobots.com" # the base hostname & protocol for your site
twitter_username: playwithrobots
github_username:  playwithrobots
disqus_shortname: playwithrobots
global_comments_enabled: true
facebookLikeBox: true
# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/


gems:
  - jekyll-redirect-from
  - jekyll-sitemap
